### ISSUE TITLE
Cannot read property 'queue' of undefined

### ISSUE THREAD

**Issue by rogsme** [colestrode/hubot-deploy-queue#32]
Hi. I'm getting this error when trying "deploy add". What could be happening? 

I installed hubot-deploy-queue like this:

`npm install --save git+https://github.com/colestrode/hubot-deploy-queue.git`

Thanks.

**Comment by jasonrhodes** [comment]
Heh, we haven't ended up using this so I've no idea if it works end-to-end but it sounds like you're missing the robot brain (Redis connection). Are you running Redis and using https://github.com/hubot-scripts/hubot-redis-brain ?

Or any kind of "hubot brain"?

**Comment by rogsme** [comment]
@jasonrhodes Yes, you where right :+1: Thank you

**Comment by jasonrhodes** [comment]
:+1:
