### ISSUE TITLE
Persist deploy queue

### ISSUE THREAD

**Issue by colestrode** [colestrode/hubot-deploy-queue#5]
The queue is lost whenever hubot restarts. Let's add some sweet redis persistence.

**Comment by jasonrhodes** [comment]
This is weird. It should persist by nature of being attached to `robot.brain` ...

**Comment by jasonrhodes** [comment]
Oh wait I think it's just because:

``` javascript
robot.brain.deployQueue = [];

// instead of
robot.brain.deployQueue = robot.brain.deployQueue || [];
```

:)

**Comment by colestrode** [comment]
if only I had a brain

**Comment by jasonrhodes** [comment]
My refactor PR is almost ready, dont fix this yet! Lol

**Comment by colestrode** [comment]
I was so tempted :) But held off
